/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoListsRouteImport } from './routes/todo-lists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodoListsIndexRouteImport } from './routes/todo-lists.index'
import { Route as TodoListsListIdRouteImport } from './routes/todo-lists.$listId'
import { Route as LoginSuccessRouteImport } from './routes/login.success'

const TodoListsRoute = TodoListsRouteImport.update({
  id: '/todo-lists',
  path: '/todo-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoListsIndexRoute = TodoListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodoListsRoute,
} as any)
const TodoListsListIdRoute = TodoListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => TodoListsRoute,
} as any)
const LoginSuccessRoute = LoginSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/todo-lists': typeof TodoListsRouteWithChildren
  '/login/success': typeof LoginSuccessRoute
  '/todo-lists/$listId': typeof TodoListsListIdRoute
  '/todo-lists/': typeof TodoListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/login/success': typeof LoginSuccessRoute
  '/todo-lists/$listId': typeof TodoListsListIdRoute
  '/todo-lists': typeof TodoListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/todo-lists': typeof TodoListsRouteWithChildren
  '/login/success': typeof LoginSuccessRoute
  '/todo-lists/$listId': typeof TodoListsListIdRoute
  '/todo-lists/': typeof TodoListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/todo-lists'
    | '/login/success'
    | '/todo-lists/$listId'
    | '/todo-lists/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/login/success' | '/todo-lists/$listId' | '/todo-lists'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/todo-lists'
    | '/login/success'
    | '/todo-lists/$listId'
    | '/todo-lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRouteWithChildren
  TodoListsRoute: typeof TodoListsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo-lists': {
      id: '/todo-lists'
      path: '/todo-lists'
      fullPath: '/todo-lists'
      preLoaderRoute: typeof TodoListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo-lists/': {
      id: '/todo-lists/'
      path: '/'
      fullPath: '/todo-lists/'
      preLoaderRoute: typeof TodoListsIndexRouteImport
      parentRoute: typeof TodoListsRoute
    }
    '/todo-lists/$listId': {
      id: '/todo-lists/$listId'
      path: '/$listId'
      fullPath: '/todo-lists/$listId'
      preLoaderRoute: typeof TodoListsListIdRouteImport
      parentRoute: typeof TodoListsRoute
    }
    '/login/success': {
      id: '/login/success'
      path: '/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof LoginSuccessRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginSuccessRoute: typeof LoginSuccessRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSuccessRoute: LoginSuccessRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface TodoListsRouteChildren {
  TodoListsListIdRoute: typeof TodoListsListIdRoute
  TodoListsIndexRoute: typeof TodoListsIndexRoute
}

const TodoListsRouteChildren: TodoListsRouteChildren = {
  TodoListsListIdRoute: TodoListsListIdRoute,
  TodoListsIndexRoute: TodoListsIndexRoute,
}

const TodoListsRouteWithChildren = TodoListsRoute._addFileChildren(
  TodoListsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRouteWithChildren,
  TodoListsRoute: TodoListsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
