/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoListsRouteImport } from './routes/todo-lists'
import { Route as IndexRouteImport } from './routes/index'

const TodoListsRoute = TodoListsRouteImport.update({
  id: '/todo-lists',
  path: '/todo-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo-lists': typeof TodoListsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo-lists': typeof TodoListsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todo-lists': typeof TodoListsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo-lists'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo-lists'
  id: '__root__' | '/' | '/todo-lists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodoListsRoute: typeof TodoListsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo-lists': {
      id: '/todo-lists'
      path: '/todo-lists'
      fullPath: '/todo-lists'
      preLoaderRoute: typeof TodoListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodoListsRoute: TodoListsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
